from __future__ import annotations

from typing import Any, Dict, List

import pandas as pd
import streamlit as st

class Visualizer:
    """
    Premium visualization helpers for modernization metrics and outputs.
    """

    def render_headline_metrics(self, metrics: Dict[str, Any]) -> None:
        c1, c2, c3, c4, c5 = st.columns(5)
        self._metric_card(
            c1,
            "Findings",
            metrics.get("total_findings", 0),
            "Repo-wide modernization signals",
        )
        self._metric_card(
            c2,
            "Recommendations",
            metrics.get("total_recommendations", 0),
            "Generated by the strategy engine",
        )
        self._metric_card(
            c3,
            "Auto Applied",
            metrics.get("auto_patch_count", metrics.get("auto_applied_count", 0)),
            "Governance-approved safe changes",
        )
        self._metric_card(
            c4,
            "Governance Blocks",
            metrics.get("governance_block_count", 0),
            "Changes requiring manual control",
        )
        self._metric_card(
            c5,
            "Progress Score",
            metrics.get("modernization_progress_score", 0.0),
            "Run-level automation progress",
        )

    def render_operating_context(self, result: Dict[str, Any]) -> None:
        st.markdown('<div class="premium-card">', unsafe_allow_html=True)
        st.markdown('<div class="section-title">Run Context</div>', unsafe_allow_html=True)

        caps = result.get("available_capabilities", []) or []
        pills = "".join(
            f'<span class="pill pill-blue">{cap}</span>' for cap in caps
        ) or '<span class="pill pill-slate">No capabilities detected</span>'

        st.markdown(
            f"""
            <div style="margin-bottom:0.55rem;"><strong>Repository Access Mode:</strong> {result.get("repo_access_mode", "unknown")}</div>
            <div style="margin-bottom:0.55rem;"><strong>Scan Mode:</strong> {result.get("scan_mode", "unknown")}</div>
            <div style="margin-bottom:0.8rem;"><strong>Repository Root:</strong> <code>{result.get("repo_root", "")}</code></div>
            <div><strong>Available Capabilities</strong></div>
            <div style="margin-top:0.45rem;">{pills}</div>
            """,
            unsafe_allow_html=True,
        )
        st.markdown("</div>", unsafe_allow_html=True)

    def render_category_breakdown(self, metrics: Dict[str, Any]) -> None:
        st.markdown('<div class="premium-card">', unsafe_allow_html=True)
        st.markdown('<div class="section-title">Findings by Category</div>', unsafe_allow_html=True)
        st.markdown('<div class="section-caption">Frontend, backend, config, and architecture distribution.</div>', unsafe_allow_html=True)
        data = metrics.get("findings_by_category", {})
        if not data:
            st.info("No category metrics available.")
        else:
            df = pd.DataFrame([{"category": k, "count": v} for k, v in data.items()])
            st.bar_chart(df.set_index("category"))
        st.markdown("</div>", unsafe_allow_html=True)

    def render_recommendation_breakdown(self, metrics: Dict[str, Any]) -> None:
        st.markdown('<div class="premium-card">', unsafe_allow_html=True)
        st.markdown('<div class="section-title">Recommendations by Type</div>', unsafe_allow_html=True)
        st.markdown('<div class="section-caption">Modernization strategy output by proposal class.</div>', unsafe_allow_html=True)
        data = metrics.get("recommendations_by_type", {})
        if not data:
            st.info("No recommendation metrics available.")
        else:
            df = pd.DataFrame([{"proposal_type": k, "count": v} for k, v in data.items()])
            st.bar_chart(df.set_index("proposal_type"))
        st.markdown("</div>", unsafe_allow_html=True)

    def render_risk_breakdown(self, metrics: Dict[str, Any]) -> None:
        st.markdown('<div class="premium-card">', unsafe_allow_html=True)
        st.markdown('<div class="section-title">Governed Actions by Risk</div>', unsafe_allow_html=True)
        st.markdown('<div class="section-caption">Risk posture after policy evaluation.</div>', unsafe_allow_html=True)
        data = metrics.get("governed_actions_by_risk", {})
        if not data:
            st.info("No risk metrics available.")
        else:
            df = pd.DataFrame([{"risk_level": k, "count": v} for k, v in data.items()])
            st.bar_chart(df.set_index("risk_level"))
        st.markdown("</div>", unsafe_allow_html=True)

    def render_top_impacted_files(self, metrics: Dict[str, Any]) -> None:
        st.markdown('<div class="premium-card">', unsafe_allow_html=True)
        st.markdown('<div class="section-title">Top Impacted Files</div>', unsafe_allow_html=True)
        st.markdown('<div class="section-caption">Files with the highest combined finding and recommendation load.</div>', unsafe_allow_html=True)
        top_files = metrics.get("top_impacted_files", []) or []
        if not top_files:
            st.info("No impacted file data available.")
        else:
            st.dataframe(top_files, use_container_width=True)
        st.markdown("</div>", unsafe_allow_html=True)

    def render_execution_summary(self, patch_plans: List[Dict[str, Any]]) -> None:
        st.markdown('<div class="premium-card">', unsafe_allow_html=True)
        st.markdown('<div class="section-title">Execution Summary</div>', unsafe_allow_html=True)
        st.markdown('<div class="section-caption">Patch strategies, execution state, and output summary.</div>', unsafe_allow_html=True)

        if not patch_plans:
            st.info("No patch plans available.")
        else:
            rows = []
            for plan in patch_plans:
                rows.append(
                    {
                        "File": plan.get("file_path", ""),
                        "Strategy": plan.get("strategy", ""),
                        "Auto Applied": plan.get("auto_applied", False),
                        "Summary": plan.get("summary", ""),
                    }
                )
            st.dataframe(rows, use_container_width=True)
        st.markdown("</div>", unsafe_allow_html=True)

    def render_findings_table(self, findings: List[Dict[str, Any]]) -> None:
        st.markdown('<div class="premium-card">', unsafe_allow_html=True)
        st.markdown('<div class="section-title">Findings Explorer</div>', unsafe_allow_html=True)
        st.markdown('<div class="section-caption">Repository-level issues discovered by semantic analysis.</div>', unsafe_allow_html=True)

        if not findings:
            st.info("No findings available.")
        else:
            rows = []
            for item in findings:
                rows.append(
                    {
                        "File": item.get("file_path", ""),
                        "Category": item.get("category", ""),
                        "Subcategory": item.get("subcategory", ""),
                        "Severity": item.get("severity", ""),
                        "Line": item.get("line", ""),
                        "Title": item.get("title", ""),
                        "Source": item.get("source_tool", ""),
                    }
                )
            st.dataframe(rows, use_container_width=True)
        st.markdown("</div>", unsafe_allow_html=True)

    def render_recommendations_table(self, recommendations: List[Dict[str, Any]]) -> None:
        st.markdown('<div class="premium-card">', unsafe_allow_html=True)
        st.markdown('<div class="section-title">Recommendations Explorer</div>', unsafe_allow_html=True)
        st.markdown('<div class="section-caption">Proposed modernization actions from the strategy layer.</div>', unsafe_allow_html=True)

        if not recommendations:
            st.info("No recommendations available.")
        else:
            rows = []
            for item in recommendations:
                rows.append(
                    {
                        "File": item.get("file_path", ""),
                        "Proposal Type": item.get("proposal_type", ""),
                        "Title": item.get("title", ""),
                        "Current State": item.get("current_state", ""),
                        "Proposed State": item.get("proposed_state", ""),
                        "Risk Hint": item.get("risk_hint", ""),
                        "Auto Applicable": item.get("auto_applicable", False),
                    }
                )
            st.dataframe(rows, use_container_width=True)
        st.markdown("</div>", unsafe_allow_html=True)

    def render_diff_panels(self, diffs: List[Dict[str, Any]]) -> None:
        if not diffs:
            return

        st.markdown('<div class="premium-card">', unsafe_allow_html=True)
        st.markdown('<div class="section-title">Diff Preview</div>', unsafe_allow_html=True)
        st.markdown('<div class="section-caption">Unified diffs for generated or applied changes.</div>', unsafe_allow_html=True)

        for item in diffs:
            with st.expander(item.get("file_path", "diff"), expanded=False):
                st.code(item.get("diff", ""), language="diff")
        st.markdown("</div>", unsafe_allow_html=True)

    def _metric_card(self, container, label: str, value: Any, note: str) -> None:
        with container:
            st.markdown(
                f"""
                <div class="metric-shell">
                    <div class="metric-label">{label}</div>
                    <div class="metric-value">{value}</div>
                    <div class="metric-note">{note}</div>
                </div>
                """,
                unsafe_allow_html=True,
            )